# -*- coding: utf-8 -*-
"""firts_ia.ipynb

Automatically generated by Colab.

"""

# Importacion de las bibliotecas necesarias 
import tensorflow as tf
import numpy as np

# Definimos los datos y las salidas esperadas
celcius = np.array([-40, -10, 0, 8, 15, 22, 38], dtype=float)
fahrenheit = np.array([-40, 14, 32, 46, 59, 72, 100], dtype=float)

# Añadimos la primera "neurona" al modelo
capa = tf.keras.layers.Dense(units=1, input_shape=[1])
modelo = tf.keras.Sequential([capa])

# Añadimos un optimizador y la funcion de perdida para ajustar los pesos y cesgos
modelo.compile(
    # Taza de aprendizaje en (0.1)
    optimizer = tf.keras.optimizers.Adam(0.1),

    # Funcion de perdida (Error cuadratico medio)
    loss = 'mean_squared_error'
)

# Entrenamiento del modelo, epochs=1000 (Mil vueltas, para entrenar el modelo)
historial = modelo.fit(celcius, fahrenheit, epochs=1000, verbose=False)
print("Modelo Entrenado")

# Que tan mal estan los resultados de la red en cada vuelta
import matplotlib.pyplot as plt
plt.xlabel('# Epoca')
plt.ylabel('Magnitud de perdida')
plt.plot(historial.history["loss"])

# Formula para calcular los grados fahrenheit
def celcius_a_fahrenheit(c):
  f = c * 1.8 + 32
  return f

# Ejemplo de prediccion
print("Hagamos una prediccion...")
dato = float(input("Ingresa un grado celcius: "))
resultado = modelo.predict(np.array([dato]))
print(f'Resultado de la IA: {resultado}\nResultado real: {celcius_a_fahrenheit(dato)}')
